import type { Metadata } from "next";
import "./globals.css";

import { Kanit, Mitr, Prompt } from "next/font/google";

export const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const mitr = Mitr({
  subsets: ["thai", "latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});
export const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${kanit.className} ${mitr.className} ${prompt.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
